package vista.mapper.claves;

public enum ClaveEnum 
{
	ALFIL_BLANCO_BLANCO,
	TORRE_BLANCO_BLANCO,
	CABALLO_BLANCO_BLANCO,
	REY_BLANCO_BLANCO,
	REINA_BLANCO_BLANCO,
	PEON_BLANCO_BLANCO,
	
	ALFIL_NEGRO_BLANCO,
	TORRE_NEGRO_BLANCO,
	CABALLO_NEGRO_BLANCO,
	REY_NEGRO_BLANCO,
	REINA_NEGRO_BLANCO,
	PEON_NEGRO_BLANCO,
	
	ALFIL_BLANCO_NEGRO,
	TORRE_BLANCO_NEGRO,
	CABALLO_BLANCO_NEGRO,
	REY_BLANCO_NEGRO,
	REINA_BLANCO_NEGRO,
	PEON_BLANCO_NEGRO,
	
	ALFIL_NEGRO_NEGRO,
	TORRE_NEGRO_NEGRO,
	CABALLO_NEGRO_NEGRO,
	REY_NEGRO_NEGRO,
	REINA_NEGRO_NEGRO,
	PEON_NEGRO_NEGRO
	;

}
